spring.application.name=healthcare
spring.datasource.url=jdbc:postgresql://localhost:5432/HealthCare_Thivanka
spring.datasource.username=postgres
spring.datasource.password=24055252
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update